name: Itz-Workflow

on:
  push:
    branches: [main]

env: 
  NODE_VERSION_VARIABLE: '14'

jobs:
  mongo_test:
    runs-on: ubuntu-latest

    services:
      mongoDB:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: notes_app_db
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps: 
      - name: checkout branch
        uses: actions/checkout@v3

      - name: install nodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_VARIABLE }}

      - name: run node install
        run: npm install

      - name: run integration tests
        run: npm run integTest
